# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('host', models.CharField(max_length=30)),
                ('starting_chips', models.IntegerField()),
                ('pot', models.IntegerField())
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='identification_number')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('room_id', models.ForeignKey('Room', on_delete=models.CASCADE)),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('chips', models.IntegerField()),
                ('last_bet', models.IntegerField())
            ],
        )
    ]
